---
title: "RAROC-Analysis"
output: html_document
date: "2025-04-15"
---

#Loading packages
```{r}
library(dplyr)
library(reshape)
library(ggplot2)
library(nlme)
library(Hmisc)
library(tidyverse)
library(stats)
library(scales)
library(FinCal)
library(waterfalls)
library(cowplot)
library(grid)
library(ggbrace)
library(patchwork)
library(pBrackets)
library(gridGraphics)
library(gridSVG)
```

#Basic setup
```{r}
# Suppress summarise info
options(dplyr.summarise.inform = FALSE)
options(tidyverse.quiet = TRUE)

ITFcolours<- c(
  "#1f77b4",  # strong blue
  "#d62728",  # bold red
  "#5fa00a",  # strong green
  "#ff7f0e",  # vivid orange
  "#9867dd",  # medium purple
  "#aaa000",  # lime yellow
  "#081ed3",  # turquoise
  "#390b79",  # deep indigo
  "#af1493",  # deep pink
  "#ff1147",  # tomato red
  "#2A6B1A",  # forest green
  "#ffcc00",  # bright yellow
  "#19998f",  # teal green
  "#e377c2",  # vibrant pink
  "#9f4500"   # orange-red
)

# Working directory: anchored on this Rmd's folder (portable across machines)
get_script_dir <- function() {
  ki <- try(knitr::current_input(dir = TRUE), silent = TRUE)
  if (!inherits(ki, "try-error") && !is.null(ki) && nzchar(ki)) return(dirname(ki))
  if (requireNamespace("rstudioapi", quietly = TRUE) && rstudioapi::isAvailable()) {
    p <- rstudioapi::getSourceEditorContext()$path
    if (nzchar(p)) return(dirname(p))
  }
  getwd()
}
script_dir <- get_script_dir()
```

#Preparing the input data
```{r}
input_dir   <- file.path(script_dir, "Inputs")
raroc_input <- file.path(script_dir, "Inputs", "RAROC")
output_dir  <- script_dir
```

```{r}
#Other inputs from https://theicct.org/wp-content/uploads/2021/11/tco-bets-europe-1-nov21.pdf

#General for NPV:
ownership_time <- 5 #years
discount_rate <- 0.095
discount_rate_public <- 0.045
interest_rate <- 0.06
upfront_cost <- 0.2 #Variable added for sensitivity analysis
residual_value <- 0.3 
subsidy <- 0 

#Fixed costs:
registration_fee<- 800 #[Eur] // Value for France
DT_price <- data.frame( #[Eur]
  year = c(2024, 2030),
  price = c(134100, 137300)) 

BET_price <- read.csv(file.path(input_dir, "BET-Price-IEA_adjusted.csv")) %>% #Source: https://iea.blob.core.windows.net/assets/0aa4762f-c1cb-4495-987a-25945d6de5e8/GlobalEVOutlook2025.pdf adjusted with projections from https://theicct.org/wp-content/uploads/2021/11/tco-bets-europe-1-nov21.pdf
  dplyr::rename(year = Year, price = BET.Retail.Price..Eur.)
  
#Variable costs or parameters:
ownership_tax <- 950 #[Eur/year] // Value for France
road_use_charge <- 0 #[Eur/year] // Value for France
road_tolls <- 0.32 #[Eur/km] // Value for France
maintenance_costs <- data.frame( #[Eur/100km]
  fuel = c("diesel", "BET"),
  Maintenance_costs = c(18.5, 13.24)
)

diesel_consumption <- data.frame( #[l/100km]
  year = c(2024, 2030),
  fuel_consumption = c(27.7, 27.15) #Source: IICT adjusted with IEA trends 
)

energy_consumption <- data.frame( #[kWh/km]
  year = c(2020, 2030),
  energy_consumption = c(1.38, 0.99)
  )

diesel_price <- data.frame( #[Eur/l]
  year= c(2020,2030),
  price = c(0.905, 0.905)
)

electricity_price <- data.frame( #[Eur/kWh]
  year = c(2020, 2030),
  price = c(0.369, 0.127)
)

VKT_year <- read.csv(file.path(input_dir, "VKT_perYear.csv")) %>% #Source: https://theicct.org/wp-content/uploads/2021/11/tco-bets-europe-1-nov21.pdf
  dplyr::rename(service_year = Service.year, VKT = VKT..km.)
```


#Interpolating data between years

```{r}
years_to_interpolate = 2020:2035

DT_price <- approx(x=DT_price$year, y=DT_price$price, xout = 2024:2030, method = "linear", rule = 2) %>% 
  as.data.frame() %>%
  dplyr::rename (year = x, price = y)
 
diesel_consumption <- approx(x=diesel_consumption$year, y=diesel_consumption$fuel_consumption, xout = 2024:2035, method = "linear", rule = 2) %>% 
  as.data.frame() %>%
  dplyr::rename (year = x, fuel_consumption = y)

energy_consumption <- approx(x=energy_consumption$year, y=energy_consumption$energy_consumption, xout = years_to_interpolate, method = "linear", rule = 2) %>% 
  as.data.frame() %>%
  dplyr::rename (year = x, energy_consumption = y)

diesel_price <- approx(x=diesel_price$year, y=diesel_price$price, xout = years_to_interpolate, method = "linear", rule = 2) %>% 
  as.data.frame() %>%
  dplyr::rename (year = x, price = y)

electricity_price <- approx(x=electricity_price$year, y=electricity_price$price, xout = years_to_interpolate, method = "linear", rule = 2) %>% 
  as.data.frame() %>%
  dplyr::rename (year = x, price = y)
```

## -------- GET incentive to reduce TCO -----

```{r}
get_TCO_detailed <- function(Purchase_year, interest, Fuel, upfront_cost, residual_value, subsidy_type, subsidy, road_tolls_exemp){

    
  if (Fuel == "diesel"){
    vehicle_price <- DT_price$price[DT_price$year==Purchase_year]
  }else if (Fuel == "BET"){
    vehicle_price <- BET_price$price[BET_price$year==Purchase_year]
  }
  
  #SUBSIDY
  if(subsidy_type == "fixed_percentage") {
    subsidy_value <- subsidy*vehicle_price
  } else if (subsidy_type == "percentage_difference") {
    vehicle_price_diesel <- DT_price$price[DT_price$year==Purchase_year]
    subsidy_value <- (vehicle_price - vehicle_price_diesel)*subsidy
  } else if (subsidy_type == "fixed_amount"){
    vehicle_price_diesel <- DT_price$price[DT_price$year==Purchase_year]
    if (subsidy <= (vehicle_price - vehicle_price_diesel)){
      subsidy_value <- subsidy
    } else {
      subsidy_value <- (vehicle_price - vehicle_price_diesel)
    }
  }
  
  total_loan <- (vehicle_price-subsidy_value)*(1-upfront_cost)
  annual_payment <- pmt(
    r=interest/12, n=ownership_time*12, pv=-total_loan, fv=0)*12 
  
  cash_flow_detailed <- data.frame()
  
  for (year_ow in 0:ownership_time) {
    
    #Checking toll exemption
    if(Purchase_year + year_ow <= road_tolls_exemp){
      toll_exemp <- 0 #Exempted
    }else {
      toll_exemp <- 1 #No_exempted
    }
    
    if (year_ow == 0) {
      vehicle_purchase <- (vehicle_price-subsidy_value)*upfront_cost
      taxes <- registration_fee
      maintenance <- 0
      tolls <- 0
      fuel_consumption <- 0
      
    } else {
      VKT <- VKT_year$VKT[VKT_year$service_year == year_ow]
      
      vehicle_purchase <- annual_payment
      taxes <- ownership_tax + road_use_charge
      maintenance <- maintenance_costs$Maintenance_costs[maintenance_costs$fuel == Fuel]*VKT/100
      tolls <- road_tolls*VKT*toll_exemp
      
      if (Fuel == "diesel") {
        fuel_consumption <- diesel_consumption$fuel_consumption[diesel_consumption$year == Purchase_year] *
          VKT * diesel_price$price[diesel_price$year == (Purchase_year + year_ow - 1)] / 100
      } else if (Fuel == "BET") {
        fuel_consumption <- energy_consumption$energy_consumption[energy_consumption$year == Purchase_year] *
          VKT * electricity_price$price[electricity_price$year == (Purchase_year + year_ow - 1)]
      }
      
    }
    
    if (year_ow == ownership_time) {
      vehicle_purchase <- vehicle_purchase-vehicle_price*residual_value
    } else {
      vehicle_purchase <- vehicle_purchase
    }
    
    cash_flow_detailed <- rbind(
      cash_flow_detailed,
      data.frame(
        year = year_ow,
        vehicle_purchase = vehicle_purchase,
        taxes = taxes,
        maintenance = maintenance,
        tolls = tolls,
        fuel_consumption = fuel_consumption
      )
    )
    
  }
  
  NPV_detailed = data.frame(
    vehicle_purchase = npv(r = discount_rate, cf = cash_flow_detailed$vehicle_purchase),
    taxes = npv(r = discount_rate, cf = cash_flow_detailed$taxes),
    maintenance = npv(r = discount_rate, cf = cash_flow_detailed$maintenance),
    tolls = npv(r = discount_rate, cf = cash_flow_detailed$tolls),
    fuel_consumption = npv(r = discount_rate, cf = cash_flow_detailed$fuel_consumption)

  ) %>%
    mutate(NPV = vehicle_purchase + taxes + maintenance + tolls + fuel_consumption) 
  
  
  return(NPV_detailed)
  
}
```


```{r}
get_NPV_fin_instrument <- function(Purchase_year, subsidy_type, subsidy, interest_high, interest_low, residual_value, road_tolls_exemp, second_hand_value) {
  
  vehicle_price <- BET_price$price[BET_price$year==Purchase_year] #Calculating the vehicle price
  vehicle_price_diesel <- DT_price$price[DT_price$year==Purchase_year] #Calculating the price of diesel truck
  
  
  #SUBSIDY
  if(subsidy_type == "fixed_percentage") {
    subsidy_value <- subsidy*vehicle_price
  } else if (subsidy_type == "percentage_difference") {
    subsidy_value <- (vehicle_price - vehicle_price_diesel)*subsidy
  } else if (subsidy_type == "fixed_amount"){
    if (subsidy <= (vehicle_price - vehicle_price_diesel)){
      subsidy_value <- subsidy
    } else {
      subsidy_value <- (vehicle_price - vehicle_price_diesel)
    }
  }

  total_loan <- (vehicle_price-subsidy_value)*(1-upfront_cost) #Estimating the total loan
  annual_payment_high <- pmt(
    r=interest_high/12, n=ownership_time*12, pv=-total_loan, fv = 0)*12
  
  annual_payment_low <- pmt( #Annual payment with low interest
    r=interest_low/12, n=ownership_time*12, pv=-total_loan, fv =0)*12 
  
  financial_instrument <- data.frame() 
   
  for (year_ow in 0:ownership_time) { #Running the calculations for the ownership period
    
    #Checking toll exemption
    if(Purchase_year + year_ow <= road_tolls_exemp){
      toll_exemp <- 0 #Exempted
    }else {
      toll_exemp <- 1 #No_exempted
    }
    
    if (year_ow == 0) { 
      
      remaining_balance_high <- (vehicle_price-subsidy_value)*upfront_cost #Here, I am making interests independent to the subsidy because I want to evaluate the financial instruments individually.
      remaining_balance_low <- (vehicle_price-subsidy_value)*upfront_cost #Here, I am making interests independent to the subsidy because I want to evaluate the financial instruments individually.
      purchase_subsidy = subsidy_value
      tolls_subsidy <- 0
      interest_subsidy <- 0
      residual_value_subsidy <- 0
      
    } else {
      VKT <- VKT_year$VKT[VKT_year$service_year == year_ow]
      
      purchase_subsidy <- 0
      tolls_subsidy <- road_tolls*VKT*(1-toll_exemp)
      
      interest_high_paid <- remaining_balance_high * interest_high #Interest paid with high interest
      interest_low_paid <- remaining_balance_low * interest_low #Interest paid with  low interest
      
      interest_subsidy <- interest_high_paid - interest_low_paid #Subsidy on interests
      
      remaining_balance_high <- remaining_balance_high - (annual_payment_high - interest_high_paid) #Remaining debt balance to recalculate interests
      remaining_balance_low <- remaining_balance_low - (annual_payment_low - interest_low_paid)
      
      if (year_ow == ownership_time) {
        residual_value_subsidy <- vehicle_price*(residual_value - second_hand_value) #Only considered in the last year
      } else {
        residual_value_subsidy <- 0
      }

    }
    
    financial_instrument <- rbind( #Adding the results to the dataframe
      financial_instrument,
      data.frame(
        year = year_ow,
        purchase_subsidy = purchase_subsidy,
        tolls_subsidy = tolls_subsidy,
        interest_subsidy = interest_subsidy,
        residual_value_subsidy = residual_value_subsidy
      )
    )
    
  }
  
  NPV_financial_instrument = data.frame( #Calculate NPV
    purchase_subsidy = npv(r = discount_rate_public, cf = financial_instrument$purchase_subsidy),
    tolls_subsidy = npv(r = discount_rate_public, cf = financial_instrument$tolls_subsidy),
    interest_subsidy = npv(r = discount_rate_public, cf = financial_instrument$interest_subsidy),
    residual_value_subsidy = npv(r = discount_rate_public, cf = financial_instrument$residual_value_subsidy)
  ) 
  
  return(NPV_financial_instrument)

}
```

##--------------- RAROC AND RoE ------------

```{r}
PD <- readRDS(file.path(raroc_input, "PD_WB.rds"))

recovery_rate <- readRDS(file.path(raroc_input, "RecoveryRate_WB.rds"))


CB <- readRDS(file.path(raroc_input, "CentralBank_WB.rds")) %>%
  mutate(Value = Value/100) %>%
  filter(!is.na(Region.wb))

OpCosts <- readRDS(file.path(raroc_input, "OperationalCost_WB.rds"))
```

#FUNCTION TO CALCULATE THE INTEREST NEEDED TO REACH CERTAIN LEVEL OF RETURN ON EQUITY

```{r}
## Followed methodology: https://roopya.money/introduction-to-loan-pricing-and-raroc-risk-adjusted-return-on-capital/
###OUTPUT: INTEREST RATE
get_interest_raroc <- function(Purchase_year, Fuel, upfront_cost, subsidy, residual_value, PD, region, company){
  
  if (company == "SME") {
    data_RR <- recovery_rate %>% 
      select(Region, RR_industrial) %>%
      dplyr::rename(RR = "RR_industrial")
  } else if (company == "industry"){
    data_RR <- recovery_rate %>% 
      select(Region, RR_SMEs) %>%
      dplyr::rename(RR = "RR_SMEs")
  } else if (company == "Market"){
    data_RR <- recovery_rate %>% 
      select(Region, RR)
  }
  
  if (Fuel == "Diesel") {
    vehicle_price <- DT_price$price[DT_price$year == Purchase_year]
    
    RecoveryRate <- data_RR$RR[data_RR$Region == region]
    
  } else if (Fuel == "BET") {
    vehicle_price <- BET_price$price[BET_price$year == Purchase_year]
    RecoveryRate <- residual_value
  }
  
  total_loan <- (1 - upfront_cost - subsidy) * vehicle_price 

  
  LGD <- 1 - RecoveryRate #Source: https://www.investopedia.com/terms/l/lossgivendefault.asp
  EL <- total_loan*PD*LGD #Expected loss
  
  Economic_capital_requirement <- 0.08
  
  Cost_capital <- CB$Value[CB$Region.wb == region]

  Economic_capital = Economic_capital_requirement*total_loan
  
  raroc <- 0.1
  
  Op_expenses <- OpCosts$Value[OpCosts$Region.wb == region]

  NII <- (raroc*Economic_capital + EL)/(1-Op_expenses)
  
  interest_rate_output <- (NII + Cost_capital*Economic_capital)/total_loan
  
  return(interest_rate_output)
}
```

# Function to calculate the incentive required to reach a TCO reduction goal

```{r}
find_incentive <- function(TCO_reduction_goal, year, incentive_type, guess_value) {
  
  #Pre-setting variables to change
  residual_value <- 0
  subsidy <- 0
  road_tolls_exemp <- 0
  
  interest_new <- get_interest_raroc(Purchase_year = year, Fuel="BET", upfront_cost = upfront_cost, subsidy = subsidy, residual_value = residual_value, PD = PD_BET_before, region = "Europe", company = "industry")
  
  baseline_TCO_result <- get_TCO_detailed(
    Purchase_year = year, 
    interest = interest_new,
    Fuel = "BET",
    upfront_cost = upfront_cost,
    residual_value = residual_value,
    subsidy_type = "fixed_percentage",
    subsidy = subsidy,
    road_tolls_exemp = road_tolls_exemp
  )
  
  baseline_TCO <- baseline_TCO_result$NPV
  target_TCO <- baseline_TCO * (1-TCO_reduction_goal)

  # Update the parameter based on the input
  if (incentive_type == "subsidy") {
    subsidy <- guess_value
  } else if (incentive_type == "residual_value") {
    residual_value <- guess_value
  } else if (incentive_type == "tolls") {
    road_tolls_exemp <- guess_value
  }
  
  interest_new <- get_interest_raroc(Purchase_year = year, Fuel="BET", upfront_cost = upfront_cost, subsidy = subsidy, residual_value = residual_value, PD = PD_BET_after, region = "Europe", company = "industry")
  
  
  #Estimating the new TCO
  TCO_estimated <- get_TCO_detailed(
    Purchase_year = year,
    interest = interest_new,
    Fuel = "BET",
    upfront_cost = upfront_cost,
    residual_value = residual_value,
    subsidy_type = "fixed_percentage", 
    subsidy = subsidy,
    road_tolls_exemp = road_tolls_exemp
  )
  
  return(TCO_estimated$NPV-target_TCO)
}
```

```{r}
subsidy_results <- data.frame()

for (year in c(2024, 2027, 2030)) {
  
  if (year == 2024) {
    PD_BET_before <- PD$PD_industrial[PD$Region == "Europe"] *2
    PD_BET_after <- PD$PD_industrial[PD$Region == "Europe"] *2
  } else if (year == 2027) {
    PD_BET_before <- PD$PD_industrial[PD$Region == "Europe"] *1.7
    PD_BET_after <- PD$PD_industrial[PD$Region == "Europe"] *1.7
  } else if (year == 2030) {
    PD_BET_before <- PD$PD_industrial[PD$Region == "Europe"] *1.5
    PD_BET_after <- PD$PD_industrial[PD$Region == "Europe"] *1.5
  }
  
  subsidy_solution <- uniroot(
    function(guess_value) find_incentive(TCO_reduction_goal = 0.1, 
                                         year = year, 
                                         incentive_type = "subsidy", 
                                         guess_value),
    interval = c(0, 1),
    tol = 1e-6)
  
  IR_new <- get_interest_raroc(Purchase_year = year, Fuel="BET", upfront_cost = upfront_cost, subsidy = subsidy_solution$root, residual_value = 0, PD = PD_BET_after, region = "Europe", company = "industry") #Calculating the IR with the new incentive for estimating the NPV
  
  NPV_gov = get_NPV_fin_instrument(Purchase_year=year, 
                                   subsidy_type = "fixed_percentage", 
                                   subsidy = subsidy_solution$root, 
                                   interest_high = IR_new, 
                                   interest_low = IR_new, 
                                   residual_value = 0, 
                                   road_tolls_exemp=0, 
                                   second_hand_value=0)
  
  subsidy_results <- rbind(subsidy_results,
                           data.frame( year = year, 
                                       subsidy_req = subsidy_solution$root, 
                                       NPV_gov = NPV_gov$purchase_subsidy))
}

```

```{r}
rvg_results <- data.frame()

for (year in c(2024, 2027, 2030)) {
  #PD before and after ...
  
  if (year == 2024) {
    PD_BET_before <- PD$PD_industrial[PD$Region == "Europe"] *2
    PD_BET_after <- PD$PD_industrial[PD$Region == "Europe"] *2
  } else if (year == 2027) {
    PD_BET_before <- PD$PD_industrial[PD$Region == "Europe"] *1.7
    PD_BET_after <- PD$PD_industrial[PD$Region == "Europe"] *1.7
  } else if (year == 2030) {
    PD_BET_before <- PD$PD_industrial[PD$Region == "Europe"] *1.5
    PD_BET_after <- PD$PD_industrial[PD$Region == "Europe"] *1.5
  }
  
  for (second_hand_value in seq(0, 0.3, by = 0.001)){
    rvg_solution <- uniroot(
      function(guess_value) find_incentive(TCO_reduction_goal = 0.1, 
                                           year = year, 
                                           incentive_type = "residual_value", 
                                           guess_value),
      interval = c(0, 1), 
      tol = 1e-6)
    
    IR_new <- get_interest_raroc(Purchase_year = year, Fuel="BET", upfront_cost = upfront_cost, subsidy = 0, residual_value = rvg_solution$root, PD = PD_BET_after, region = "Europe", company = "industry") #Calculating the IR with the new incentive for estimating the NPV
    
    NPV_gov = get_NPV_fin_instrument(Purchase_year=year, 
                                     subsidy_type = "fixed_percentage", 
                                     subsidy = 0, 
                                     interest_high = IR_new, 
                                     interest_low = IR_new, 
                                     residual_value = rvg_solution$root, 
                                     road_tolls_exemp=0, 
                                     second_hand_value=second_hand_value)
    
    rvg_results <- rbind(rvg_results,
                         data.frame( year = year, 
                                     rvg_req = rvg_solution$root,
                                     second_hand_value = second_hand_value,
                                     NPV_gov = NPV_gov$residual_value_subsidy))
  }
}
```


## Plotting the results:
```{r}
year_map <- c("2024" = 1, "2027" = 2, "2030" = 3)
subsidy_results$x_custom <- year_map[as.character(subsidy_results$year)]
rvg_results$x_custom <- year_map[as.character(rvg_results$year)]

rvg_plot <- ggplot() +

  geom_tile(
    data = rvg_results %>%
      mutate(NPV_gov = case_when(NPV_gov <= 0 ~ 0,
                                 .default = NPV_gov)),
    aes(x = x_custom, y = NPV_gov, fill = second_hand_value),
    width = 0.23, height = 500  
  ) +
  scale_fill_gradient(
    name = "Gov. expenditure to complete \nthe RVG, with a BET RV of*:",
    low = ITFcolours[2], high = ITFcolours[3],
    breaks = c(0.0, 0.1, 0.2, 0.3), 
    labels = function(x) {
      paste0("with ", round(x * 100), "%")
    }) +
  
  geom_segment(
    data = subsidy_results,
    aes(x = x_custom - 0.15, 
        xend = x_custom + 0.15,
        y = NPV_gov, 
        yend = NPV_gov, 
        color = "Purchase subsidy"),
    linetype = "solid",
    linewidth = 1.3
  ) +
  
  geom_segment(
    data = rvg_results %>%
      filter(second_hand_value==0.25,
             year == 2024),
    aes(x = x_custom - 0.3, 
        xend = x_custom + 0.15,
        y = NPV_gov, 
        yend = NPV_gov),
    color = "black",
    linetype = "dashed",
    linewidth = 0.6
  ) +
  
  geom_text(
    data = rvg_results %>%
      filter(second_hand_value==0.25,
             year == 2024),
    aes(x = x_custom + 0.2, y = NPV_gov, label = "RV = 25%"),
    hjust = 0.08, vjust = 0, size = 3, lineheight = 0.8
  ) +
  
  guides(
    color = guide_legend(order = 1),
    fill = guide_colorbar(order = 2, 
                          reverse = TRUE)
  ) +
  
  scale_color_manual(values=c("Purchase subsidy" = ITFcolours[1])) +
  scale_y_continuous(labels = function(x) format(x, big.mark = " "),
                     breaks = c(seq(0, 85000, 20000), 2750),
                     limits = c(0,85000),
                     expand = c(0, 0))+
  scale_x_continuous(
    breaks = 1:3,
    labels = c("2024", "2027", "2030"),
    expand = c(0, 0)) +
  
  labs(#title="Subsidy vs RVG:\nGovernment's expenditure to reduce TCO by 10%",
    title = NULL,
    y="Government expenditure (€/BET)",
    x="Year of purchase",
    color = "",
    caption = "RV: Resale Value.\n* as a % of the initial purchase price") +
  
  theme_classic() +
  coord_fixed(3/85000) + 
  theme(
    legend.justification = c("left", "top"),
    legend.text = element_text(size = 8), 
    legend.title = element_text(size = 8),
    plot.caption = element_text(
      hjust = 0,  
      size = 8,
      face = "italic", 
      margin = margin(t = 10) 
    )
  )


rvg_plot
```

```{r}
# Convert ggplot to grob
rvg_grob <- ggplotGrob(rvg_plot)

# Draw everything
grid.newpage()
grid.draw(rvg_grob)

# Draw the brace in npc coordinates relative to the panel
grid.brackets(
  x1 =unit(0.765, "npc"), y1 =  unit(0.66, "npc"),
  x2 = unit(0.765, "npc"), y2 = unit(0.38, "npc"),
  col = "black",
  lwd = 1.1
)

grid::grid.text(
  "BEV resale value\n(% of initial purchase price)",
  x = unit(0.8, "npc"), y = unit(0.52, "npc"), just = "left", gp = grid::gpar(cex = 0.65)
)

```



